# Generated by Django 3.0.7 on 2020-07-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
