# Generated by Django 3.0.7 on 2020-07-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bidder',
            new_name='bidder_id',
        ),
    ]
